#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo 'Husky pre-commit hook is working!'
npm run lint; npm run format; npm test
npm run lint && npm run format && npm test
npm run lint && npm run format && npm test --passWithNoTests
